### PR TITLE
Career

### PR DESCRIPTION
**Pull request by omeiregman**

### CODE REVIEW

**Comment by ikenna** [comment]
Good work Godsman and pair. 👍 . Looks good. 

Please make the following amendments: 
1. The user cannot see any label for the 'Date of Birth'  field  on the 'Personal Details' page of the form. Please add this. 
2. On the 'Personal Details' form, change 'State of Origin' to 'State'. 
3. Remove the Country drop down from the 'Personal Details' page. For now, all our users are in Nigeria. 
4. Replace  'Contact Address' into 3 separate fields with the following labels: 'Address Line 1', 'Address Line 2 (Optional)' and 'Address Line 3 (Optional)'. 
5. Make the 'Education' and 'Work Experience' fields bigger text areas. They should each be about 20 rows at least. 
6. Fix the git conflict issues with the pull request, to prepare it for merging. 

Looking forward to seeing your changes.

**Comment by ikenna** [comment]
@omeiregman : Can you resolve the conflicts so I can merge the PR ? Click on 'command line instructions' above if you want to learn how to do this. Other resources that can help you: 

https://githowto.com/resolving_conflicts
https://www.youtube.com/watch?v=iRyUUGsNHrU

**Comment by omeiregman** [comment]
I have tried doing that, but i'm not getting positive results. I will consult Azeez on the issue this morning.

**Comment by ikenna** [comment]
Still has conflicts. You can ask Ridwan to help you with resolving conflicts. 

Also saw some commented out code on email validation. I don't like commented out code, except you have a very good reason for leaving it there. So please if you must leave that there, let me know why you need it.

**Pull request closed without merging**
