### PR TITLE
Team 4 submitting school profile form

### PR DESCRIPTION
**Pull request by Abwas**

### CODE REVIEW

**Comment by ikenna** [comment]
Is this pull request different from https://github.com/sweskills/kuti/pull/6 ? As far as I can see they look similar. 

I expect each pair to raise only pull request, not two. It doesn't matter which member of the pair raises the pull request, because I can see the 2 people who worked on it via Trello.

**Comment by ikenna** [comment]
Let me know if this is different in any way. If its not different, then just close the pull request, as its a duplication.

**Comment by Abwas** [comment]
Ok noted but this is the main pull request for the team, the other was done as instructed by Femi. Will go ahead and close it then i.e. #6.  Thanks

**Comment by ikenna** [comment]
👍 Good work

**Pull request merged**
